Numpy Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.

In [5]:
import numpy as np
a = np.array([[1, 2, 3],[4,5,6]]) #2-D Array
print("a: ",a)
b=np.array([[7, 8, 9],[10,11,12]]) #2-D Array
print("b: ",b)
print("Shape of a: ",a.shape)
print("Shape of b: ",b.shape)

c=np.vstack((a,b))
print("Row Stack: ")
print(c)

d=np.hstack((a,b))
print("Col Stack: ")
print(d)

a:  [[1 2 3]
 [4 5 6]]
b:  [[ 7  8  9]
 [10 11 12]]
Shape of a:  (2, 3)
Shape of b:  (2, 3)
Row Stack: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Col Stack: 
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [18]:
a = np.array([1, 2, 3,4,5,6]) #2-D Array
print("a: ",a)
b=np.array([5,6,7,8,9,10]) #2-D Array
print("b: ",b)
n= len(a)
m= len(b)
for i in range(n):
    for j in range(m):
        if a[i]==b[j]:
            print("Common Elemnt is at ",i+1,"index in a and ",j+1,"index in b ",a[i],",",b[j])

a:  [1 2 3 4 5 6]
b:  [ 5  6  7  8  9 10]
Common Elemnt is at  5 index in a and  1 index in b  5 , 5
Common Elemnt is at  6 index in a and  2 index in b  6 , 6


Using built function intersect1d()

In [19]:
import numpy as np
a= np.array([1,2,3,4,5,6])
b= np.array([5,6,7,8,9])
cmn_ele=np.intersect1d(a,b)

print("common elements ", cmn_ele)

common elements  [5 6]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [30]:
import numpy as np
a= np.array([1,2,3,4,5,6,10,15,20,50,65,80,100])

i=np.where((a>4) & (a<11)) #This will find all indices at which the value of a is b/w 5 and 10 (inclusive)
print(i) #Prints indices
print(a[i]) #Prints values at indices


(array([4, 5, 6], dtype=int64),)
[ 5  6 10]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [50]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')
col_names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
condition = (iris[:, 2] > 1.5) & (iris[:, 0] < 5.0)
output = []
output = iris[condition]
print(output)


[[4.8 3.4 1.6 0.2 nan]
 [4.8 3.4 1.9 0.2 nan]
 [4.7 3.2 1.6 0.2 nan]
 [4.8 3.1 1.6 0.2 nan]
 [4.9 2.4 3.3 1.  nan]
 [4.9 2.5 4.5 1.7 nan]]


Pandas Questions

5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).

In [56]:
import pandas as pd
url='https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df=pd.read_csv(url)
filter = df.iloc[::20,[df.columns.get_loc('Manufacturer'), df.columns.get_loc('Model'), df.columns.get_loc('Type')]]
print(filter)




   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.

DF before replacing min and max:

In [45]:
import pandas as pd
url='https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df=pd.read_csv(url)
df.head(10)

Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small       12.9   15.9       18.8      25.0   
1          NaN      Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi          90  Compact       25.9   29.1       32.3      20.0   
3         Audi         100  Midsize        NaN   37.7       44.6      19.0   
4          BMW        535i  Midsize        NaN   30.0        NaN      22.0   
5        Buick     Century  Midsize       14.2   15.7       17.3      22.0   
6        Buick     LeSabre    Large       19.9   20.8        NaN      19.0   
7        Buick  Roadmaster    Large       22.6   23.7       24.9      16.0   
8        Buick     Riviera  Midsize       26.3   26.3       26.3      19.0   
9     Cadillac     DeVille    Large       33.0   34.7       36.3      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

DF after replacing minprice and maxprice with respective avg:

In [50]:
import pandas as pd
url='https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df=pd.read_csv(url)
avg_min_price=df['Min.Price'].mean()
avg_max_price=df['Max.Price'].mean()
df['Min.Price'].fillna(avg_min_price,inplace=True)
df['Max.Price'].fillna(avg_max_price,inplace=True)
df.head(10)


Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN      Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi          90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi         100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW        535i  Midsize  17.118605   30.0  21.459091      22.0   
5        Buick     Century  Midsize  14.200000   15.7  17.300000      22.0   
6        Buick     LeSabre    Large  19.900000   20.8  21.459091      19.0   
7        Buick  Roadmaster    Large  22.600000   23.7  24.900000      16.0   
8        Buick     Riviera  Midsize  26.300000   26.3  26.300000      19.0   
9     Cadillac     DeVille    Large  33.000000   34.7  36.300000      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

7. How to get the rows of a dataframe with row sum > 100?

In [2]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print("df before filter: \n",df)
filter=df[df.sum(axis=1)>100]
print("\n df after filter: \n",filter)


df before filter: 
      0   1   2   3
0   34  12  14  14
1   10  19  37  20
2   16  37  12  16
3   29  13  12  14
4   38  33  10  27
5   23  13  29  33
6   22  38  14  31
7   26  23  21  14
8   20  19  34  37
9   13  27  20  23
10  12  38  14  24
11  22  17  19  31
12  12  17  16  19
13  24  23  32  29
14  10  37  27  27

 df after filter: 
      0   1   2   3
4   38  33  10  27
6   22  38  14  31
8   20  19  34  37
13  24  23  32  29
14  10  37  27  27
